[package]
name = "rustid-hooks"
edition.workspace = true
version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
moka = { workspace = true }
reqwest = { workspace = true }
rustid-core = { path = "../rustid-core" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
tokio = { workspace = true }
