[package]
name = "rustid-fuzz"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
rustid-core = { path = "../rustid-core" }
rustid-saml = { path = "../rustid-saml" }
rustid-server = { path = "../rustid-server" }
axum = { workspace = true }
base64 = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
